#!/usr/bin/env bash
# create file, echo text, delete file

pid_file="/var/run/myscript.pid"

terminator() {
	rm "$pid_file"
	exit
}
echo "$$" > "$pid_file"

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator"' SIGTERM
	trap 'terminator' SIGQUIT
done
